apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: server
  type: LoadBalancer
